name: Classy
main: Main.Main
version: 1
commands:
   Making:
      description: This is a demo command.
      usage: /<command>
   Hurt:
      description: This is a demo command.
      usage: /<command>
   nick:
      description: This is a demo command.
      usage: /<command> [player]
   test:
      description: This is a demo command.
      usage: /<command> [player]
   i:
      description: This is a demo command.
      usage: /<command> [name] [amount]
   fly:
      description: This is a demo command.
      usage: /<command>
   bp:
      description: This is a demo command.
      usage: /<command>
   ban:
      description: This is used to ban a player.
      usage: /<command> <name>
   unban:
      description: This is used to unban a banned player.
      usage: /<command> <name>
   vers:
      description: This is used to unban a banned player.
      usage: /<command>
   debug:
      description: This is used to unban a banned player.
      usage: /<command>
   trade:
      description: This is used to unban a banned player.
      usage: /<command>
   friends:
      description: This is used to unban a banned player.
      usage: /<command>